name: Build LoudMouth

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: LoudMouth-Windows.exe
            build_command: pyinstaller --onefile --windowed --name="LoudMouth-Windows" --add-data "models;models" main.py
          - os: ubuntu-latest
            artifact_name: LoudMouth-Linux
            build_command: |
              sudo apt-get update
              sudo apt-get install portaudio19-dev
              pyinstaller --onefile --windowed --name="LoudMouth-Linux" --add-data "models:models" main.py
          - os: macos-latest
            artifact_name: LoudMouth-macOS
            build_command: |
              brew install portaudio
              pyinstaller --onefile --windowed --name="LoudMouth-macOS" --add-data "models:models" main.py

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build executable
      run: ${{ matrix.build_command }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/${{ matrix.artifact_name }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          LoudMouth-Windows.exe/LoudMouth-Windows.exe
          LoudMouth-Linux/LoudMouth-Linux
          LoudMouth-macOS/LoudMouth-macOS
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 